version: '3.4'

services:
#  p1-db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: password
#    volumes:
#      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
#    ports:
#      - 5432:5432
  mtgdex:
    image: mtgdex
    depends_on:
      - p1-db
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
